#!/usr/bin/env python

import sys
import pathlib, shutil

path = pathlib.Path('~/Downloads').expanduser()

IMG = ['.png', '.jpg', '.jpeg']
CODE = ['.sh', '.py', '.js', '.c', '.cpp', '.html']
DOC = ['.pdf', '.doc', '.docx', '.djvu']
ISO = ['.iso', '.img']
ARCH = ['.zip', '.tar', '.gz', '.bz2']

DIRS = ['Images', 'Code', 'Doc', 'Iso', 'Archives']

if not path.exists():
    path.mkdir()
    sys.exit()

for folder in DIRS:
    if not (path / folder).exists():
        (path / folder).mkdir()

for item in path.iterdir():
    if item.is_file() and item.suffix.lower() in IMG:
        img_path = path / DIRS[0] / item.name
        if not img_path.exists():
            shutil.move(str(item), str(img_path))
    if item.is_file() and item.suffix.lower() in CODE:
        code_path = path / DIRS[1] / item.name
        if not code_path.exists():
            shutil.move(str(item), str(code_path))
    if item.is_file() and item.suffix.lower() in DOC:
        doc_path = path / DIRS[2] / item.name
        if not doc_path.exists():
            shutil.move(str(item), str(doc_path))
    if item.is_file() and item.suffix.lower() in ISO:
        iso_path = path / DIRS[3] / item.name
        if not iso_path.exists():
            shutil.move(str(item), str(iso_path))
    if item.is_file() and item.suffix.lower() in ARCH:
        archive_path = path / DIRS[4] / item.name
        if not archive_path.exists():
            shutil.move(str(item), str(archive_path))
